export const GET_DASHBOARD_DATA_START = 'GET_DASHBOARD_DATA_START'
export const GET_DASHBOARD_DATA_SUCCESS = 'GET_DASHBOARD_DATA_SUCCESS'
export const GET_DASHBOARD_DATA_FAILURE = 'GET_DASHBOARD_DATA_FAILURE'

export const GET_FEED_DATA_START = 'GET_FEED_DATA_START'
export const GET_FEED_DATA_SUCCESS = 'GET_FEED_DATA_SUCCESS'
export const GET_FEED_DATA_FAILURE = 'GET_FEED_DATA_FAILURE'

export const ADD_FEED_START = 'ADD_FEED_START'
export const ADD_FEED_SUCCESS = 'ADD_FEED_SUCCESS'
export const ADD_FEED_FAILURE = 'ADD_FEED_FAILURE'

export const GET_CRON_DATA_START = 'GET_CRON_DATA_START'
export const GET_CRON_DATA_SUCCESS = 'GET_CRON_DATA_SUCCESS'
export const GET_CRON_DATA_FAILURE = 'GET_CRON_DATA_FAILURE'

export const GET_ARTICLE_DATA_START = 'GET_ARTICLE_DATA_START'
export const GET_ARTICLE_DATA_SUCCESS = 'GET_ARTICLE_DATA_SUCCESS'
export const GET_ARTICLE_DATA_FAILURE = 'GET_ARTICLE_DATA_FAILURE'

export const GET_GRAPH_DATA_START = 'GET_GRAPH_DATA_START'
export const GET_GRAPH_DATA_SUCCESS = 'GET_GRAPH_DATA_SUCCESS'
export const GET_GRAPH_DATA_FAILURE = 'GET_GRAPH_DATA_FAILURE'

export const GET_LOGS_DATA_START = 'GET_LOGS_DATA_START'
export const GET_LOGS_DATA_SUCCESS = 'GET_LOGS_DATA_SUCCESS'
export const GET_LOGS_DATA_FAILURE = 'GET_LOGS_DATA_FAILURE'

export const DEVICE_DETECT = 'DEVICE_DETECT'
export const DASHBOARD_LAYOUT_CHANGE = 'DASHBOARD_LAYOUT_CHANGE'
export const DASHBOARD_LAYOUT_CHANGE_MOBILE = 'DASHBOARD_LAYOUT_CHANGE_MOBILE'

export const USER_SIGNUP_START = 'USER_SIGNUP_START'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE'

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const GET_BOARDS_START = 'GET_BOARDS_START'
export const GET_BOARDS_SUCCESS = 'GET_BOARDS_SUCCESS'
export const GET_BOARDS_FAILURE = 'GET_BOARDS_FAILURE'

export const SET_APP_LOADING = 'SET_APP_LOADING'
export const SET_APP_LOADED_FAILURE = 'SET_APP_LOADED_FAILURE'
export const OPEN_SNACKBAR_ACTION = 'OPEN_SNACKBAR_ACTION'
