export const GET_DASHBOARD_DATA_START = "GET_DASHBOARD_DATA_START";
export const GET_DASHBOARD_DATA_SUCCESS = "GET_DASHBOARD_DATA_SUCCESS";
export const GET_DASHBOARD_DATA_FAILURE = "GET_DASHBOARD_DATA_FAILURE";

export const GET_FEED_DATA_START = "GET_FEED_DATA_START";
export const GET_FEED_DATA_SUCCESS = "GET_FEED_DATA_SUCCESS";
export const GET_FEED_DATA_FAILURE = "GET_FEED_DATA_FAILURE";

export const GET_ARTICLE_DATA_START = "GET_ARTICLE_DATA_START";
export const GET_ARTICLE_DATA_SUCCESS = "GET_ARTICLE_DATA_SUCCESS";
export const GET_ARTICLE_DATA_FAILURE = "GET_ARTICLE_DATA_FAILURE";