export const DASHBOARD_ROUTE_PATH = '/dashboard*'
export const HOME_ROUTE_PATH = '/dashboard/home'
export const FEEDS_ROUTE_PATH = '/dashboard/feeds'
export const ARTICLES_ROUTE_PATH = '/dashboard/articles'
export const CRONJOBS_ROUTE_PATH = '/dashboard/cronjobs'
export const LOGS_ROUTE_PATH = '/dashboard/logs'
export const BOARDS_ROUTE_PATH = '/dashboard/boards'

export const HOMEPAGE_ROUTE_PATH = '/user*'
export const LOGIN_ROUTE_PATH = '/user/login'
export const SIGNUP_ROUTE_PATH = '/user/signup'
